# Generated by Django 4.2 on 2023-05-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.course')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.staff')),
            ],
        ),
    ]
