# Generated by Django 4.2 on 2023-05-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='App.course'),
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='App.course'),
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='dep',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='App.department'),
        ),
    ]
