# Generated by Django 4.2 on 2023-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_attendance_report_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
