# Generated by Django 4.2 on 2023-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_attendance_report_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
