# Generated by Django 4.2 on 2023-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_attendance_report_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='is_present',
            field=models.CharField(max_length=100),
        ),
    ]
